### PR TITLE
Encode assertion url command

### PR DESCRIPTION
**Pull request by neilherbertuk**
Removed createBase64AssertionUrl.php and created a new console command to encode assertion urls

```bash
   $ php artisan laravel-saml:encodeurl https://sp.webapp.com/saml/login
   --
   URL Given: https://sp.webapp.com/saml/login
   Encoded AssertionURL:aHR0cHM6Ly9zcC53ZWJhcHAuY29tL3NhbWwvbG9naW4=
```

Updated README.md and comments within config to detail new method of generating base_64 encoded  assertion urls

### CODE REVIEW

**Comment by steve-ks** [comment]
Great thing ! I should have also thought about creating an artisan command. Propably I was lazy...

**Comment by steve-ks** [comment]
I just had the idea that making this even more adorable by directly adding the encoded URL to the saml config file as a new entry, adding maybe also some flags for also including a destination and an issuer. The config:cache should be rebuild anyways afterward, might also be a direct step.

I might check this out next week, as I have hardly time left this week.

**Comment by neilherbertuk** [comment]
I need to figure out how best to create a PR for this, I might have to re-fork your master branch. Take a look at my fork, I've added configurable attribute assertions allowing each SP to have it's own config for what user model attributes can be sent to the SP along with a few other config options per sp.

**Comment by steve-ks** [comment]
Sounds all great. Did you do a pull request or do you want to keep this separate in your fork with the configurable SP options ? 

Anyhow, don't stress yourself with autoloading new SP assertion URLs if you don't have time. I could do it next week.

**Comment by SquareBeard** [comment]
Any plan to integrate the configurable attribute assertions from the fork ? It is a must have, the hardcoded name and email wont work for everyone.

**Comment by neilherbertuk** [comment]
@SquareBeard It's on my to do list. I messed up the fork with merges so do plan on re-forking and reapplying my changes to make it easier to merge in as a PR to the original.

**Pull request merged**
